<?php

namespace DreamFactory\Core\ApiBuilder\Models;

use DreamFactory\Core\Models\BaseSystemModel;
use DreamFactory\Core\Models\Service;

class ApiDefinition extends BaseSystemModel
{
    protected $table = 'api_builder_api';

    protected $fillable = [
        'name',
        'label',
        'description',
        'base_path',
        'status',
        'version',
        'metadata',
    ];

    protected $guarded = [
        'id',
        'created_date',
        'last_modified_date',
        'created_by_id',
        'last_modified_by_id',
    ];

    protected $casts = [
        'id'       => 'integer',
        'metadata' => 'array',
    ];

    protected $rules = [
        'name'      => 'required|regex:/(^[A-Za-z0-9_\-]+$)+/',
        'label'     => 'string|max:80',
        'base_path' => 'required|regex:/(^[A-Za-z0-9_\-]+$)+/',
        'status'    => 'in:draft,published,archived',
    ];

    public static function boot()
    {
        parent::boot();

        // Renaming the URL segment moves the API to a new service name; drop the
        // service for the old name before the new one is synced below.
        static::updating(function (ApiDefinition $api) {
            if ($api->isDirty('base_path')) {
                $old = trim((string)$api->getOriginal('base_path'), '/');
                if ($old !== '') {
                    $api->removeServiceInstance($old);
                }
            }
            return true;
        });

        static::saved(function (ApiDefinition $api) {
            $api->syncServiceInstance();
            return true;
        });

        // Deleting an API removes its published service — just like deleting any
        // other DreamFactory service-backed API.
        static::deleted(function (ApiDefinition $api) {
            $api->removeServiceInstance();
            return true;
        });
    }

    public function services()
    {
        return $this->hasMany(ApiServiceLink::class, 'api_id');
    }

    public function removeServiceInstance(?string $name = null): void
    {
        $serviceName = $name ?? trim((string)$this->base_path, '/');
        if (empty($serviceName)) {
            return;
        }

        $service = Service::whereName($serviceName)->first();
        if (
            $service
            && $service->type === 'api_builder'
            && (int)array_get((array)$service->config, 'api_id') === (int)$this->id
        ) {
            $service->delete();
        }
    }

    public function syncServiceInstance(): void
    {
        $serviceName = trim($this->base_path, '/');
        if (empty($serviceName)) {
            return;
        }

        $service = Service::whereName($serviceName)->first();
        if (!$service) {
            $service = new Service();
            $service->name = $serviceName;
            $service->type = 'api_builder';
        }

        if ($service->type !== 'api_builder') {
            return;
        }

        $service->label = $this->label ?: $this->name;
        $service->description = $this->description ?: 'Built API generated by API Builder.';
        $service->is_active = $this->status !== 'archived';
        $service->config = ['api_id' => $this->id];
        $service->save();
    }
}
